### ISSUE TITLE
trait bound not satisfied

### ISSUE THREAD

**Issue by wseaton** [jorgecarleitao/arrow2-derive#5]
Hey! This seems to be exactly what I need for translating structured log data that I've packed into structs cleanly into the arrow format, so I'm really excited by the potential of this crate. 

I seem to be getting an issue in my project: 
```
error[E0277]: the trait bound `arrow2::array::struct_::StructArray: From<LogDataArray>` is not satisfied
  --> src/main.rs:37:35
   |
37 | #[derive(Debug, Clone, PartialEq, StructOfArrow)]
   |                                   ^^^^^^^^^^^^^ the trait `From<LogDataArray>` is not implemented for `arrow2::array::struct_::StructArray`
   | 
  ::: /home/weaton/.cargo/git/checkouts/arrow2-derive-1c9d82f1d5ff8f2d/d4f7231/src/lib.rs:9:24
   |
9  | pub trait ArrowStruct: Into<StructArray> {
   |                        ----------------- required by this bound in `ArrowStruct`
   |
   = help: the following implementations were found:
             <arrow2::array::struct_::StructArray as From<arrow2::array::growable::structure::GrowableStruct<'a>>>
             <arrow2::array::struct_::StructArray as From<arrow2::record_batch::RecordBatch>>
   = note: required because of the requirements on the impl of `Into<arrow2::array::struct_::StructArray>` for `LogDataArray`
   = note: this error originates in the derive macro `StructOfArrow` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Any idea what could causing this? When I drop my struct definition into your test suite it compiles, which is causing me to scratch my head. 

Here's my cargo.toml entry, am I missing something silly? 
```
arrow2-derive = { git = "https://github.com/jorgecarleitao/arrow2-derive.git", branch = "main" }
```

Thanks again for your work on this!

**Comment by jorgecarleitao** [comment]
Hey, @wseaton ! Thanks for trying this! this is really blending edge stuff: I am still learning how to do work with macros.

With that said, do you have a minimal struct that reproduces this? I think that you are doing everything right, tbh, and there is a bug here.

**Comment by wseaton** [comment]
@jorgecarleitao no problem, I figured since the crate was so new :slightly_smiling_face: 

Here's my struct def + imports
```rust
use arrow2::datatypes::{DataType, Field};
use arrow2::{array::*, record_batch::RecordBatch};
use arrow2_derive::{ArrowStruct, StructOfArrow};

#[derive(Debug, Clone, PartialEq, StructOfArrow)]
#[arrow2_derive = "Default, Debug"]
pub struct LogData {
    time: String,
    query: String,
    user: String,
    db: String,
    pid: i32,
    xid: i32,
    uid: i32,
}

impl LogData {
    #[allow(clippy::too_many_arguments)]
    pub fn new (
        time: String,
        query: String,
        user: String,
        db: String,
        pid: i32,
        xid: i32,
        uid: i32,
    ) -> Self {
        Self {
            time, 
            query,
            user,
            db,
            pid,
            xid,
            uid
        }
    }
}
```

**Comment by jorgecarleitao** [comment]
That compiles on my machine; is the hash d4f723180fa12b8990859921f7a24d5f10ed6de8 ?

I suspect that this is because I force-pushed to the main at some point (sorry, was still prototyping and slipped me).  Could you try `cargo clean && rm Cargo.lock && cargo build`?

**Comment by wseaton** [comment]
Hmm I've `cargo updated` and I'm on the `d4f7231` hash, running the clean and re-build didn't help and neither did switching my project toolchain to nightly.  I'm also depending on `lambda_runtime` so it isn't a typical build environment

**Comment by jorgecarleitao** [comment]
strange :/ 

I've just added CI in #6 so that we can run it independently, and I have PRed your example in #7 to see how it goes.

**Comment by jorgecarleitao** [comment]
Very strange :/ I can't reproduce it on github: https://github.com/jorgecarleitao/arrow2-derive/pull/7/checks?check_run_id=3405253520 .

**Comment by jorgecarleitao** [comment]
I found why!

The `arrow2` dependency in the `Cargo.toml` must match the one declared in `arrow2-derive`'s own Cargo, or `StructArray` used by `arrow2-derive` does not match the `StructArray` used by your own crate. uf.

**Comment by wseaton** [comment]
Oof! That is strange that a wildcard resolve doesn't work.

**Comment by jorgecarleitao** [comment]
cargo does not consider github as releases: dependency resolution in cargo is based on what is in `crates.io` only. For git links, they must be provided explicitly.
